### PR TITLE
Neo4jrb version up from 7.1.4 to 9.4.0

### PR DESCRIPTION
**Pull request by JunOkumura**
- Update neo4jrb.
- Fix how to open neo4j session.
- Delete for nodes should use query `MATCH(n) DETACH DELETE n`. DatabaseCleaner is not support neo4jrb 9.4.0.
- Has_n define should be once. Fix load lib order in spec.
- Fix how to call transaction. Transaction must use `Neo4j::ActiveBase.run_transaction`.
- Index removed. Property option `index` will be no longer support. Index must generate schema and migrate.
- Add build settings for travis.

### CODE REVIEW

**Comment by azuchi** [comment]
please rebase and fix ci.

**Comment by JunOkumura** [comment]
I have done rebase.

**Comment by JunOkumura** [comment]
I understood that ci sayed failures.
I will try to fix. Please wait a minutes. ;)

WIP

**Comment by JunOkumura** [comment]
I fixed.
All spec passed in travis.

**Pull request merged**
